INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('9501','DISPLAY DE CHÃO BELLESA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0121','PEDRA POMES BELLE',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0187','PINCA BELLE BASIC COM 2 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0231','TIARA BELLE PEROLA PEQ C/1 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0248','ESPONJA BELLE NYLON COLLORS C/1',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0286','PIRANHA BELLE FASHION COM 1 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0330','ELAS. BELLE SILICONE TRANSP C/75',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0404','LIXA BELLE EXTRA PARDA UNHAS C/6',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0408','ESC CABELO BELLE MADEIRA REDONDA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0415','ESC CABELO BELLE ALMOF OVAL',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0422','ESC CABELO BELLE ALMOF QUADRADA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0446','ESC CABELO BELLE KEIKO',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0466','LIXA BELLE MINI PARDA UNHAS C/20',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0477','ESC CABELO BELLE MADEIRA M/LUA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0491','CORTADOR DE UNHA BELLE PEQ',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0514','PENTE DE BOLSO BELLE C/3 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0521','ESC CABELO BELLE PATA-PATA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4321','PINCEL PARA TINTURA BELLE GDE',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0552','PENTE CABO LARGO PLASTICO BELE',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0569','PENTE P-112 PROF PLASTICO BELLE',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0576','PENTE MATA MARIDO PLASTICO BELLE',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0613','ESC CABELO BELLE FLEX RETA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0620','ESC CABELO BELLE FLEX OVAL',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0640','TOUCA BELLE BANHO COMUM C/1 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0705','PENTE FINO SEM CABO BELLE',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0749','LIXA BELLE E.V.A',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0824','ELAS BELLE MEIA MARROM C/6 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0831','ELAS. BELLE MEIA COLORIDO C/6 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0848','ELAS BELLE MEIA PRETO C/6 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0879','ELAS. BELLE SILICONE PRETO C/75',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0910','ELAS. BELLE PRETO C/ENFEITE C/2',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2275','TIC-TAC BELLE PEQ PRETO C/6 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1085','CORTADOR DE UNHA BELLE GDE',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1122','GRAMPOS CAB BELLE N.5 LOIRO C/50',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1139','GRAMPOS CAB BELLE N.5 PRETO C/50',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1214','TIARA BELLE GATINHA C/1 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1382','PORTA ESCOVA DENTAL BELLE',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1542','LIXA BELLE BIG PARDA P/UNHA C/3',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1641','KIT BELLE C/ 3 PENTES PLASTICO',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1658','KIT MAN.BELLE LIXA E PALITO C/6',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1757','PALITO BELLE 2 PONTAS C/3 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1917','ESC CABELO BELLE RIGIDA OVAL',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1924','ESC CABELO BELLE RIGIDA RETA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1948','PIRANHA BELLE MED COLLORS C/2 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1955','PIRANHA BELLE PQ COLLORS C/3 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2037','PIRANHA BELLE MINI COLLORS C/3',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2075','TIARA BEL ACRILICA MED C/1',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2099','TIARA BELLE TECIDO MED PRETO C/1',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2242','MINI PIRANHA BELLE C/10 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2266','ELAS.BELLE MEIA GATINHA SORT C/3',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2280','ELAS. BELLE PEROLA C/1 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2624','LIXA SEMI CONCAVA PRETA/AMARELA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2655','SABONETEIRA BELLE FITNESS',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2747','TIC-TAC BELLE MEDIO PRETO C/6',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0039','LIXA BELLE RETA MEDIA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('873','DISPLAY DE BALCÃO BELLESA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0947','TIC-TAC PEQ COLORIDO COM 6 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0057','ELAS.BELLESA FIO TELEFONE C/2 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0886','ELAS.BELLESA SIL FLUORES C/75 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0040','PIRANHA BELLESA DOURADA SORT C/1',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2006','PIRANHA BELLESA MINI C/1 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0756','PIRANHA BELLESA PEQ C/1 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0992','PIRANHA BELLESA TARTARUGA MD C/1',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0930','PIRANHA BELLESA MEDIA C/1 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2259','PIRANHA BELLESA STYLUS C/1 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0354','TIARA TARTARUGA GROSSA C/1 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2730','TIC-TAC BELLESA GRANDE C/6 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0767','PALITO DE UNHA BELLESA INOX',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0712','ESPATULA BELLESA INOX',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1795','TOUCA BELLESA P/BANHO INF C/1 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0091','LIXA BELLESA ROMEU E JULIETA MED',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1764','PALITO BELLESA PONTA CHANFRO C/6',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0084','RALIXA BELLESA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0916','PENTE AFRO DE PLASTICO BELLESA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0668','PENTE P-112 PROF CRISTAL GLITTER',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-3164','TIARA BELLESA BANDANA LAÇO',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-3157','TIARA BELLESA BANDANA NÓ',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0213','BUCHA VEGETAL COM ESTAMPA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0237','BUCHA VEGETAL PEDAÇO',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2297','ESCOVA PARA UNHAS',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0244','ESPONJA PARA BANHO ADULTO',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0545','KIT TINTURA PINCEL+PENTE PROF',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0750','DESENCRAVADOR INOX PROFISSIONAL',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-3201','PINÇA DIAGONAL BASIC',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-3218','PINÇA RETA BASIC',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0811','TESOURA UNHA CURVA BASIC',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0804','TESOURA UNHA RETA BASIC',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-3102','ESC CABELO DESEMBARAÇANTE OVAL',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4154','KIT ESC CABELO NICE+PENTE',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4161','KIT ESC CABELO OVAL+PENTE',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4192','KIT ESC CABELO RIGIDA RETA+PENT',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-3010','BICO DE PATO METAL',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0279','ELAS FIO TELEFONE COLLORS C/2 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-3850','ELAS. MEIA PASTEL COM 6 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1108','GRAMPO CABELO N°7 LOIRO 20 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1115','GRAMPO CABELO N°7 PRETO 20 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2044','PIRANHA BIANCA 3 DENTES MEDIA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2051','PIRANHA BIANCA 4 DENTES MEDIA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-2822','PIRANHA COM STRASS COM1 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1979','PIRANHAGRANDE COM 1 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0156','TIC-TAC GRANDE COLORIDO COM 6 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0954','TIC-TAC MÉDIO COLORIDO COM 6 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0897','ELAS. LUXO SORTIDOS COM 2 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0170','ELAS MEIA COLLORS COM 4 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0855','ELAS. KIDS COLORIDO PEQUENO C/6',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4338','ELAS. KIDS GATINHA PEQUENO C/3',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4352','ELAS. KIDS LAÇO GATINHA COM 1',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0163','ELAS. KIDS MARROM PEQUENO COM 6',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4376','ELAS. KIDS POM POM GRANDE COM 1',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4369','ELAS. KIDS POM POM PEQUENO COM 2',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0862','ELAS. KIDS PRETO PEQUENO COM 6',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4345','ELAS KIDS SILICONE FLUORESCETE',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4383','MINI PIRANHAKIDS COM 10 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4390','TIARA KIDS POM POM COM 1 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-3799','KIT COM 2 PENTES PLASTICO',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4314','KIT COM 2 PENTES PLASTICO KIT 2',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1931','PENTE VENICE DE PLASTICO',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1535','LIXA BIG CANÁRIO COM 3 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-3980','LIXA BIG CINZA GR100/180 1 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0435','LIXA EXTRA CANÁRIO COM 6 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0169','LIXA PLÁSTICA BASIC',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0527','LIXA POP MINI CANÁRIO COM 20 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1504','POLIDOR GRANDE COM 1 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0251','ESPONJA PARA BANHO BELLESA KIDS',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0729','APARADOR DE CUTICULASBASIC',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1573','PIRANHABIANCA 3DENTES PEQ 1UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1610','PIRANHABIANCA 4DENTES PEQ 1UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0880','CURVEX PARA CÍLIOS BELLESA BASIC',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4482','TIARA FRU FRU TECIDO C/1',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4208','BICO DE PATO KIDS DIVERSOS 1UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4239','BICO DE PATO KIDS DIVERSOS 2UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4215','ELASTICO FAIXAKIDS DIVERSOS',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4253','TIARA BELLESA KIDS-DIVERSOS',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4185','KIT ESC RIG OVAL+ PE CABO LAR PP',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0361','BLOCO POLIDOR BELLESA COM 1 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0985','APLICADOR BASE BELLESA PIZZA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0033','ESPONJA APLICADOR BASE COXINHA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4499','SCRUNCHIES BELLESA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4550','MAS FACIAL KIDS TNT AZUL 10UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4505','MAS FACIAL KIDS TNT BRANCA 10UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4536','MAS FACIAL KIDS TNT ROSA 10UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4451','MAS TNT ADULTO BRANCA 10UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4512','MASC FACIAL KIDS TNT BRANCA 25UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4581','TIARA BANDANA JULIETTE BELLESA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-5311','TIARA BELA VELUDO',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4246','ELAS KIDS MEIA MARIA CHICA C/2',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4260','PULSEIRA KID DIVERSOS C/2 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0101','LACAROTE BELLESA C/1 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0217','ELAS KIDS FIO DE TELEFONE C/5',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-5922','TOUCA DE CETIM BELLESA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-5885','ESC CABELO BELLESA CACHOS POLVO',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-5779','ELAS BELLE MEIA SORTIDA C/6 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-5786','ELAS BELLE MEIA SORTIDA C/6 UND',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-5847','ESPONJA APLICADOR BASE GOTA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-4222','TIC-TAC KIDS SORTIDO C/6',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-5892','TIARA BELLESA PEDRAS SORTIDA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-5908','PULSEIRA MICANGA SORTIDA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-5939','ELAS FAIXA NO ADULTO SORTIDO',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-5991','PIRANHA BELLESA METAL STRASS',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-5953','COLAR E PULSEIRA KIDS MICANGA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-5946','TIARA BELLESA KIDS MICANGA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0367','PALITO DE UNHA UNHA D GATO C/2',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-1870','PENTE FINO COM CABO BELLE',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-7520','ELAS MEIA FRU FRU COLLORS C/1 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-7575','ELAS MEIA LUXO COLORIDO C/4 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-7551','ELAS MEIA LUXO COLOR CITRICO C/4',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-7568','ELAS MEIA LUXO NUDE C/4 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-7544','ELAS MEIA LUXO PASTEL C/4 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-7537','ELAS MEIA LUXO PRETO C/4 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-7667','ESC CABELO BELLESA CANDY OVAL',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-7650','ESC CABELO BELLESA CANDY RAQUETE',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-7674','ESC CABELO DESEMBA RAQUETE FLEX',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-6066','TIARA KIDS GATINHA GLITTER C/1UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-7599','TIC TAC  STILUS COLLORS C/ 3 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-6134','ELAS SILICONE MARROM C/75 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-6080','ELAS SILIC MARROM GROSSO C/50 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-6097','ELAS SILICO PRETO GROSSO C/50 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-6103','ELAS SILIC COLOR GROSSO C/50 UN',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-6110','ELAS SILIC FLUORES GROSSO C/50',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-6127','ELAS SILIC TRANSPA GROSSO C/50',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-0893','ELAS BELLE SILICON COLORIDO C/75',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-7865','ESC CABELO SUPER FLEX OVAL',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-7872','ESC CABELO SUPER FLEX QUADRADA',true,0);
INSERT INTO produto (referencia, descricao, ativo,versao) VALUES ('34-7858','ESC CABELO SUPER FLEX HEXA',true,0);
/*
SELECT
CONCAT('INSERT INTO produto (referencia, descricao, ativo,versao) VALUES (''', REFERENCIA,''',''',LTRIM(RTRIM(REPLACE( DESCRPROD, REFERENCIA , ''))),''',', IIF(ATIVO='S','true','false'),',',0,');'  )
FROM SANKHYA_PRODUCAO.sankhya.TGFPRO WHERE FABRICANTE = 'BELLESA' AND AD_PORTFOLIO = 'L'
*/